import fs from "fs/promises";
import path from "path";

/** Repository root (`blockbuster-prompt-editor/`). */
export const REPO_ROOT = path.resolve(import.meta.dirname, ".");

export const EDITOR_WORKSPACES_DIR = path.join(REPO_ROOT, "editor-workspaces");

const LEGACY_EDITOR_WORKSPACES_DIR = path.join(REPO_ROOT, ".editor-workspaces");

function normalizeRegistryRootDir(rootDir: string): string {
  return rootDir
    .replace(/\/.editor-workspaces(\/|$)/g, "/editor-workspaces$1")
    .replace(/\\\.editor-workspaces(\\|$)/g, "\\editor-workspaces$1");
}

export interface ProjectRecord {
  id: string;
  label: string;
  /** Absolute path to Remotion package root (contains remotion.config.ts). */
  rootDir: string;
  compositionId: string;
  /** File name inside src/ (e.g. RivetAd.tsx). */
  compositionModule: string;
  fps: number;
  width: number;
  height: number;
  durationInFrames: number;
  /** Glob patterns relative to src/ — only .ts / .tsx matched. */
  editableGlobs: string[];
}

export interface ProjectsRegistry {
  activeId: string;
  projects: Record<string, ProjectRecord>;
}

const REGISTRY_PATH = path.resolve(import.meta.dirname, ".editor-projects.json");
const FINGERPRINT_PATH = path.resolve(import.meta.dirname, "src", "__projects-fingerprint.ts");

const DEFAULT_RIVET: ProjectRecord = {
  id: "rivet",
  label: "Rivet (remotion-jobs)",
  rootDir: path.join(REPO_ROOT, "remotion-jobs"),
  compositionId: "RivetAd",
  compositionModule: "RivetAd.tsx",
  fps: 30,
  width: 1920,
  height: 1080,
  durationInFrames: 900,
  editableGlobs: ["**/*.ts", "**/*.tsx"],
};

export function srcDirOf(p: ProjectRecord): string {
  return path.join(p.rootDir, "src");
}

export function publicDirOf(p: ProjectRecord): string {
  return path.join(p.rootDir, "public");
}

export function versionsDirOf(p: ProjectRecord): string {
  return path.join(p.rootDir, ".editor-versions");
}

export async function touchProjectsFingerprint(): Promise<void> {
  const stamp = new Date().toISOString();
  const body =
    `// Auto-generated by editor server — do not edit by hand.\n` +
    `export const PROJECTS_FINGERPRINT = "${stamp}";\n`;
  await fs.mkdir(path.dirname(FINGERPRINT_PATH), { recursive: true });
  await fs.writeFile(FINGERPRINT_PATH, body, "utf-8");
}

/**
 * Rename `.editor-workspaces` → `editor-workspaces` and fix `.editor-projects.json` paths.
 * Vite `import.meta.glob` does not reliably include dot-prefixed workspace dirs.
 * Idempotent. Run before Vite via `npm run dev` and on first registry read.
 */
export async function ensureEditorWorkspacesMigrated(): Promise<void> {
  let renamed = false;
  try {
    await fs.access(LEGACY_EDITOR_WORKSPACES_DIR);
    let newExists = false;
    try {
      await fs.access(EDITOR_WORKSPACES_DIR);
      newExists = true;
    } catch {
      /* new dir missing */
    }
    if (!newExists) {
      await fs.rename(LEGACY_EDITOR_WORKSPACES_DIR, EDITOR_WORKSPACES_DIR);
      renamed = true;
    }
  } catch {
    /* legacy folder missing */
  }

  try {
    const raw = await fs.readFile(REGISTRY_PATH, "utf-8");
    const parsed = JSON.parse(raw) as ProjectsRegistry;
    if (!parsed.projects) {
      if (renamed) await touchProjectsFingerprint();
      return;
    }
    let changed = false;
    for (const id of Object.keys(parsed.projects)) {
      const p = parsed.projects[id];
      const next = normalizeRegistryRootDir(p.rootDir);
      if (next !== p.rootDir) {
        parsed.projects[id] = { ...p, rootDir: next };
        changed = true;
      }
    }
    if (changed) {
      await fs.writeFile(REGISTRY_PATH, JSON.stringify(parsed, null, 2), "utf-8");
      await touchProjectsFingerprint();
    } else if (renamed) {
      await touchProjectsFingerprint();
    }
  } catch {
    if (renamed) await touchProjectsFingerprint();
  }
}

export async function readRegistry(): Promise<ProjectsRegistry> {
  await ensureEditorWorkspacesMigrated();
  try {
    const raw = await fs.readFile(REGISTRY_PATH, "utf-8");
    const parsed = JSON.parse(raw) as ProjectsRegistry;
    if (!parsed.projects || typeof parsed.activeId !== "string") throw new Error("bad registry");
    return parsed;
  } catch {
    return {
      activeId: DEFAULT_RIVET.id,
      projects: { [DEFAULT_RIVET.id]: DEFAULT_RIVET },
    };
  }
}

export async function writeRegistry(reg: ProjectsRegistry): Promise<void> {
  await fs.writeFile(REGISTRY_PATH, JSON.stringify(reg, null, 2), "utf-8");
  await touchProjectsFingerprint();
}

export async function ensureRegistry(): Promise<ProjectsRegistry> {
  let reg = await readRegistry();
  let changed = false;
  if (!reg.projects[DEFAULT_RIVET.id]) {
    reg.projects[DEFAULT_RIVET.id] = DEFAULT_RIVET;
    changed = true;
  }
  if (!reg.projects[reg.activeId]) {
    reg.activeId = DEFAULT_RIVET.id;
    changed = true;
  }
  if (changed) await writeRegistry(reg);
  return reg;
}

export async function getActiveProject(): Promise<ProjectRecord> {
  const reg = await ensureRegistry();
  let p = reg.projects[reg.activeId];
  if (!p) {
    reg.activeId = DEFAULT_RIVET.id;
    await writeRegistry(reg);
    return DEFAULT_RIVET;
  }

  // If registry points at a missing tree, repoint to an existing workspace under `editor-workspaces/`.
  try {
    await fs.access(path.join(srcDirOf(p), p.compositionModule));
  } catch {
    const idNoBb = p.id.replace(/^bb-/, "");
    const candidateRoots = [
      path.join(EDITOR_WORKSPACES_DIR, p.id),
      path.join(EDITOR_WORKSPACES_DIR, idNoBb),
      path.join(EDITOR_WORKSPACES_DIR, `bb-${idNoBb}`),
      path.join(EDITOR_WORKSPACES_DIR, path.basename(p.rootDir)),
    ];
    const seen = new Set<string>();
    for (const canonRoot of candidateRoots) {
      const abs = path.resolve(canonRoot);
      if (seen.has(abs)) continue;
      seen.add(abs);
      const canonTsx = path.join(canonRoot, "src", p.compositionModule);
      try {
        await fs.access(canonTsx);
        p = { ...p, rootDir: path.resolve(canonRoot) };
        reg.projects[p.id] = p;
        await writeRegistry(reg);
        break;
      } catch {
        /* try next */
      }
    }
  }

  return p;
}

export async function setActiveProject(id: string): Promise<ProjectRecord | null> {
  const reg = await ensureRegistry();
  if (!reg.projects[id]) return null;
  reg.activeId = id;
  await writeRegistry(reg);
  return reg.projects[id];
}

/** Path from this app's `src/` to project `src/`, posix, for Vite glob / dynamic import keys. */
export function clientSrcRootRel(project: ProjectRecord): string {
  const rel = path.relative(path.join(REPO_ROOT, "src"), srcDirOf(project));
  return rel.split(path.sep).join("/");
}

function matchGlobRel(relPath: string, pattern: string): boolean {
  const norm = relPath.replace(/\\/g, "/");
  if (pattern === "**/*.ts" || pattern === "**/*.tsx" || pattern === "**/*.{ts,tsx}") {
    return norm.endsWith(".ts") || norm.endsWith(".tsx");
  }
  if (pattern.endsWith("**/*.ts")) return norm.endsWith(".ts") && !norm.endsWith(".tsx");
  if (pattern.endsWith("**/*.tsx")) return norm.endsWith(".tsx");
  return norm.endsWith(".ts") || norm.endsWith(".tsx");
}

async function walkTsFiles(dir: string, baseLen: number, out: string[]): Promise<void> {
  let entries: { name: string; isDirectory: () => boolean }[];
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch {
    return;
  }
  for (const ent of entries) {
    const full = path.join(dir, ent.name);
    const rel = full.slice(baseLen).replace(/^\//, "").replace(/\\/g, "/");
    if (ent.isDirectory()) {
      if (ent.name === "node_modules" || ent.name === "out" || ent.name === ".git") continue;
      await walkTsFiles(full, baseLen, out);
    } else if (/\.(tsx|ts)$/.test(ent.name) && !ent.name.endsWith(".d.ts")) {
      out.push(rel);
    }
  }
}

export async function listEditableRelativePaths(project: ProjectRecord): Promise<string[]> {
  const src = srcDirOf(project);
  const baseLen = src.length;
  const all: string[] = [];
  await walkTsFiles(src, baseLen, all);
  const globs = project.editableGlobs?.length ? project.editableGlobs : ["**/*.ts", "**/*.tsx"];
  return all.filter((rel) => globs.some((g) => matchGlobRel(rel, g))).sort();
}

export async function readSourceSnapshot(
  project: ProjectRecord,
  relativePaths: string[]
): Promise<Record<string, string>> {
  const src = srcDirOf(project);
  const files: Record<string, string> = {};
  for (const rel of relativePaths) {
    try {
      files[rel] = await fs.readFile(path.join(src, rel), "utf-8");
    } catch {
      /* skip */
    }
  }
  return files;
}

export async function writeSourceFile(project: ProjectRecord, relPath: string, content: string): Promise<void> {
  const full = path.join(srcDirOf(project), relPath);
  await fs.mkdir(path.dirname(full), { recursive: true });
  await fs.writeFile(full, content, "utf-8");
}
